### ISSUE TITLE
Vercel command in README.md is confusing, potential README.md improvement.

### ISSUE THREAD

**Issue by wiksien** [gumroad/shortest#29]
# Description of the issue

The README.MD documentations contains the following command:

> vercel env pull .env.development.local

This command doesn't work if a developer is not connected to already existing Vercel project.

There is no information about any existing Vercel project to link to, so the only thing developer can do is to create a new Vercel project that naturally has no environment variables set.

## Screenshots

![obraz](https://github.com/user-attachments/assets/a7fc250b-72a0-43db-83bd-b4c6d5128ee0)

## To Reproduce

1. Open your terminal
2. Clone the repository
3. Navigate to your project
4. Run the command

## Files affected

README.md

## Tasks

- [x] Discuss the solution to this issue.
- [x] Update README.MD

# Discussion

Unfortunately it costs money to add team members to a Vercel project (20$ per user per month on the Pro plan. [Vercel Pricing](https://vercel.com/pricing)).

So the best course of action in my opinion is to get rid of the vercel env pull and flesh out the instructions how to setup the development environment.

This would make it easier for developers to get started.

I'd be happy to do that, but I want to make sure it is the correct course of action, since I am totally new to this project.

**Comment by danthomps** [comment]
Hey @wiksien 👋 - I agree, the setup process is quite cumbersome for non-Gumroad team members. I've created a draft PR that includes a walkthrough in the `README.md`. You can check it out here: https://github.com/gumroad/shortest/blob/b75c12eb5c6cdf3884151aff8ffc7b3a8b07a2f5/README.md

Note that it's based on the Clerk/GitHub changes in #26, so you'll need to use that branch for the GitHub OAuth part.

While it's an improvement, I still find it a bit too manual. There's a good example of a setup script from the original repository: https://github.com/leerob/next-saas-starter/blob/main/lib/db/setup.ts — It uses the Stripe CLI and offers an option for a local Docker instance of Postgres. Clerk doesn't have an official CLI yet (it's in their roadmap backlog), but we could probably create a setup script that handles 60-70% of the overall process.

I won't have time to work on a script today, but if you'd like to give it a try, have at it!

Regarding the Anthropic API, its cost is unfortunately unavoidable. While it's relatively inexpensive, if it's not feasible for you, there are plenty of other avenues for improvements to the project that don't involve that feature.

**Comment by slavingia** [comment]
Isn't there an example of the .env you'd need to replicate? So no need to Vercel pull if you don't want to.

**Comment by wiksien** [comment]
@danthomps Thank you for the PR. Looks great. I will try to automate the process with the scrypt, will let you know how it goes in 24 hours.

When it comes to Anthropic API don't worry, I already pay for it.

**Comment by wiksien** [comment]
@slavingia Yes, but you still need to input manually all of the variables yourself and as of now there is no information where to find those in README.md. Danthomps PR fixes this, by providing a clear guide how to get all of those variables to input into the .env file.

**Comment by slavingia** [comment]
Sounds good, I'll take some of those changes and merge them into `main`.

**Comment by slavingia** [comment]
Merged those changes! @wiksien if you could have a look and let us know what you think and if we should make further changes, thanks!

**Comment by wiksien** [comment]
@slavingia Thank you for the merge! I made the setup.ts file for a smooth local dev creation experience. Feel free to check it out: #31

**Comment by slavingia** [comment]
So nice! I will come up with new to-dos tmmrw and maybe host a zoom/meet call next week!
