### ISSUE TITLE
Teams in shortest

### ISSUE THREAD

**Issue by crabest** [gumroad/shortest#55]
It sounds too early, but let's do it and build on it since it's early.

A user could create a team and invite people it in, also assigning their roles.

Let me know what do you all think.

**Comment by slavingia** [comment]
why necessary if GitHub handles this already?

**Comment by crabest** [comment]
I don't think we are going to stick with github in that use case since we can integrate multiple platforms like gitlab (I am mainly using it) unless we are going to adapt the teams intergration for each platform

**Comment by slavingia** [comment]
Why wouldn't we?

**Comment by crabest** [comment]
you mean stick with github?

**Comment by slavingia** [comment]
With the team setup of either. I don't think shortest is very multiplayer anyway, it's for devs shipping quickly and using ai on their own work, likely before asking for reviews from other team members (imo)

**Comment by crabest** [comment]
The idea for teams came in my mind to let a user have some kind of control the subscription of the users (like in cursor), and also why not having an overview of the tests generated.

I agree with that shortest is more singleplayer to let AI ship quickly, as I thought it's maybe too early, let's think of it.
