### ISSUE TITLE
Unhandled Error in Production When Generating Tests – Unable to Replicate Locally, Logs Needed

### ISSUE THREAD

**Issue by m2rads** [gumroad/shortest#61]
Hi all! I noticed an unhandled error in production today when generating new tests. I was not able to replicate this issue in my local env. 

If someone could provide the logs in Vercel would be great. 

Also it would help to check the Preview env in Vercel to see if the issue happens there as well. 

![image](https://github.com/user-attachments/assets/f602a871-159c-4d64-9d52-a2bac016980c)

***

![image](https://github.com/user-attachments/assets/f146424c-9f40-4803-bf9f-7cf793715356)

**Comment by m2rads** [comment]
I deployed my main branch to my Vercel account and it is working as expected. I am not seeing any errors in the logs. 
Would it be possible to add me to the Vercel project? I'm wondering if this is caused by configuration change. 

![image](https://github.com/user-attachments/assets/cf9f9569-6991-44b5-b309-ef6d8b07aace)

![image](https://github.com/user-attachments/assets/db73294e-c9f0-41fc-8851-110754f32eb0)

**Comment by m2rads** [comment]
@slavingia Looking at the logs seems like the API key for Anthropic is missing. I redeployed the latest version and the issue persist. Could you please add the api key again to the env vars. Let's see if this fixes generating the tests.

![image](https://github.com/user-attachments/assets/d6b894d3-0306-4635-abea-9cf43fa8aa64)

**Comment by slavingia** [comment]
added and redeploying now

**Comment by m2rads** [comment]
Monitoring the deployment, seems like all the env vars need to added again. 
I sometimes deal with the same issue. Wonder why that happens!
![image](https://github.com/user-attachments/assets/e2966e75-9500-46d5-9c0e-f79c9e5dce2e)

**Comment by slavingia** [comment]
Where are you seeing that? I'm not. It may be that those are only used on Production not on preview branches; can fix.

**Comment by m2rads** [comment]
So when a deployment fails it does not promote it to the production. If you go in Deployments page you can see your deployment history. If you click on your last deployment you can see if it was successful.

![image](https://github.com/user-attachments/assets/a5251433-8124-45d5-b065-85eb92361780)

![image](https://github.com/user-attachments/assets/bb652e04-9be1-4a7f-ae4d-a3eacce494e0)

**Comment by slavingia** [comment]
Yep, and they are all successful? So what's the issue? Could you send me the specific URL in which you're seeing those errors?

**Comment by m2rads** [comment]
Awesome! Now I can see your latest deployment was promoted to prod and the issue is resolved. I can generate the test cases again. 

![image](https://github.com/user-attachments/assets/6c669e2b-72a6-4ae4-9dfc-42a2b1195cf7)

**Comment by slavingia** [comment]
WOOT!

**Comment by m2rads** [comment]
This is the failing deployment that I was talking about: 
https://vercel.com/gumroad-dbdbd10c/shortest/5HLNpJ5wVJKa6eHRX9x7kEgV7SJv

and this is the last deployment that solved the issue: 
https://vercel.com/gumroad-dbdbd10c/shortest/FsZitCNjhYQdAXd7xM1g8PP24kiY
